### ISSUE TITLE
[需求说明] [Phase I]

### ISSUE THREAD

**Issue by wenqingyu** [OneTicketTech/NightPlus_ChatRobot#1]
### 背景介绍
NIGHT+是一个夜生活互动体验平台，我们有很多微信群用来与用户互动交流，客服问答，咨询推荐。但人工的能力非常有限，受到工作时间，反馈效率，查询速度等影响，所以我们希望通过微信机器人逐渐替代人工回复／管理微信群以及客服，咨询推荐等工作。

### Phase I 目标
- [ ] （基础搭建）机器人账号能够一次登录以后，长期稳定的运行在服务器上（请务必考虑稳定性）。
- [ ] （基础功能）机器人收到与业务不相关的问题时，也可以完成基本的回答 (可考虑图灵机器人接口)。
- [ ] （数据记录）机器人在在任何群里和个人聊天中的信息都需要记录到数据库中，以备以后分析使用
       - nickName String (来源用户微信昵称)
       - wechatId String（来源用户ID）
       - group String/ID（群来源，如果是私聊对话标注“P2P”）
       - query String（来源信息）
       - feedback [] (机器人回复用户的内容，如有多条，按顺序逐个增加即可)
       - createdAt（创建时间）
       - robotId String（回复处理机器人的ID）

- [ ] （群组管理）我们会按照城市分不同群组，如有用户新加机器人为好友，会收到机器人的关于地理位置的提问
ex: “你当前所在的城市是？” 之后根据城市拉入到对应的城市群组里
- [ ] （组群问答）当用户在群里@机器人账号后才进行回答，但针对所有信息都需要进行记录
- [ ] （相似句式匹配，渠道问题）渠道问题是指用户常问的一些问句
ex: ”今晚去哪里“，“今晚去哪玩”，“晚上那里好玩”， 这三个句子都是晚上活动推荐的问题，于是我们将“晚上活动推荐”作为一个渠道问题，根据当时的活动情况，这些渠道问题会指向具体的内容／链接。
例如：本周五我们有一个WhiskeyL的线下主推活动，我们会将跟“晚上活动推荐”相关的渠道问题指向这个线下活动的介绍文字／链接。
- [ ] 关键字抓取：当触发到预设定关键字时，推送相应的信息
ex: “K歌之王KTV怎么样”，“有谁去过K歌之王KTV” -> 给用户推送提前设定好的“K歌之王”KTV的链接
